port: 8899

db:
  type: mysql
  host: 127.0.0.1:3306
  user: root
  password: 123456
  name: chatgpt_web_new_go

redis:
  addr: 127.0.0.1:6379

gpt:
  apiKey: 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
  botDesc: You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.
  model: gpt-3.5-turbo

emailServer:
  host:
  port:
  senderName:
  user:
  password: