port: 8899

db:
  type: mysql
  host: 127.0.0.1:3306
  hostR1: 127.0.0.1:3306
  user: root
  password: yourpassword
  name: chatgpt_web_new_go

redis:
  addr: 127.0.0.1:6379
  password: yourpassword

aiClient:
  proxy: xxxxxxxxxxxxx

emailServer:
  host: "xxxxxxxxxx"
  port: "587"
  SenderName: xxxxxx
  User: xxxxxxxxx
  Password: xxxxxx
